#!/bin/bash
# CentOS 7 bootstrapping script - Configuration:

NAME=my-new-server
DOMAIN=dendory.net
EMAIL=dendory@live.ca
DNS=8.8.8.8
PROXY=
INSTALL_APACHE=true
JOIN_AD=false

echo "### Configuring hostname and networking"
echo "$NAME.$DOMAIN" > /etc/hostname
echo "search $DOMAIN" > /etc/resolv.conf
echo "domain $DOMAIN" >> /etc/resolv.conf
echo "nameserver $DNS" >> /etc/resolv.conf
echo "preserve_hostname: true" >> /etc/cloud/cloud.cfg
systemctl restart network

echo "### Disabling SELinux"
echo "SELINUX=disabled" > /etc/selinux/config
echo "SELINUXTYPE=targeted" >> /etc/selinux/config
setenforce 0

echo "### Configuring sudoers without passwords"
sed -i '/%wheel/c\%wheel ALL=(ALL) NOPASSWD: ALL' /etc/sudoers

if [ ! -z "$PROXY" ]; then
	echo "### Setting proxy"
	echo "http_proxy=$PROXY" > /etc/environment
	echo "https_proxy=$PROXY" >> /etc/environment
	echo "HTTP_PROXY=$PROXY" >> /etc/environment
	echo "HTTPS_PROXY=$PROXY" >> /etc/environment
fi

if yum list installed dnfdragora >/dev/null 2>&1; then
	echo "### Removing graphical package manager"
	yum -y remove dnfdragora
fi

echo "### Installing EPEL, other useful packages"
yum -y install wget
wget https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7 -O /tmp/RPM-GPG-KEY-EPEL-7
rpm --import /tmp/RPM-GPG-KEY-EPEL-7
wget https://archive.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -O /tmp/epel.rpm
rpm -ivh /tmp/epel.rpm
rm -f /tmp/epel.rpm
rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-1.el7.nux.noarch.rpm
wget https://dendory.net/scripts/nanorc -O /etc/nanorc
yum -y install python36 python36-devel
yum -y install python3 python3-devel
yum -y install nano scl-utils psmisc net-tools bind-utils python-pip python-devel lynx ntp
yum -y install libtool rpm-build redhat-rpm-config
yum -y install ffmpeg
yum -y install ImageMagick ImageMagick-devel
curl https://bootstrap.pypa.io/get-pip.py | python3
rm -f /usr/bin/pip
rm -f /usr/bin/pip3
ln -s /usr/bin/pip2.7 /usr/bin/pip
ln -s /usr/local/bin/pip3.6 /usr/bin/pip3
pip install mutagen ansible awscli Markdown
pip3 install pycrypto boto3 connix python-twitter youtube_dl PyNaCl discord.py twine

echo "### Disabling firewall, enabling NTP"
systemctl disable firewalld
systemctl start ntpd

if $INSTALL_APACHE ; then
	echo "### Installing Apache"
	yum -y install httpd php
	systemctl enable httpd
	systemctl start httpd
	echo "<?php phpinfo(); ?>" > /var/www/html/info.php
fi

if $INSTALL_APACHE ; then
	RESOLVED=`getent hosts $NAME.$DOMAIN`
	if [ ! -z "$RESOLVED" ]; then
		echo "### Installing LetsEncrypt"
		yum -y install python-certbot-apache certbot mod_ssl
		certbot certonly --standalone --email $EMAIL -d $NAME.$DOMAIN -w /var/www/html --agree-tos --renew-by-default -n
		mv /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.default
		wget https://dendory.net/scripts/centos-httpd-ssl.conf -O /etc/httpd/conf/httpd.conf
		sed -i "s/%HOSTNAME%/$NAME.$DOMAIN/g" /etc/httpd/conf/httpd.conf
		systemctl restart httpd
		crontab -l > /tmp/mycron
		echo "0 0 1 * * /usr/sbin/certbot renew" >> /tmp/mycron
		crontab /tmp/mycron
		rm -f /tmp/mycron
	fi
fi

if $JOIN_AD ; then
	echo "#### Joining AD domain"
	yum -y install sssd realmd oddjob oddjob-mkhomedir adcli samba-common samba-common-tools
	realm join $DOMAIN
	realm list
fi

echo "### Updating the system"
yum -y update
yum -y install yum-cron
